-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 23:09:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema my_vocabulary_book_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vocabulary_book_api` DEFAULT CHARACTER SET utf8mb4 ;
USE `vocabulary_book_api` ;

SET CHARSET utf8mb4;

-- -----------------------------------------------------
-- Table `vocabulary_book_api`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vocabulary_book_api`.`user` (
    `id` VARCHAR(128) NOT NULL COMMENT 'id',
    `mail` VARCHAR(128) NOT NULL COMMENT 'mail',
    `password` VARCHAR(64) NOT NULL COMMENT 'password',
    PRIMARY KEY (`id`, `mail`))
ENGINE = InnoDB
COMMENT = 'ユーザ';

-- -----------------------------------------------------
-- Table `vocabulary_book_api`.`user_vocabulary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vocabulary_book_api`.`user_book` (
    `id` VARCHAR(128) NOT NULL COMMENT 'id',
    `user_id` VARCHAR(64) NOT NULL COMMENT 'user_id',
    `eng` VARCHAR(64) NOT NULL COMMENT 'eng',
    `ja` VARCHAR(64) NOT NULL COMMENT 'ja',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id` ASC))
ENGINE = InnoDB
COMMENT = '単語帳';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
